import './globals.css'
import { Inter, Montserrat, Raleway } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import "tw-elements/dist/css/tw-elements.min.css";


const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
